### ISSUE TITLE
Very large production from wind or solar may override assumption that there will not be export

### ISSUE THREAD

**Issue by Richard-Deuchler** [quintel/merit#88]
The query `merit_order_total_electricity_demand.gql`describes the amount of electricity that shall be produced over the entire year. It is calculated in the following way: 

`GRAPH(final_demand_for_electricity) + GRAPH(electricity_losses_if_export_is_zero)`

It is based on the assumption that export does not occur in merit order (dispatchables are assigned only to meet domestic demand)
**However, it is very well possible that wind, solar and CHPs produce an excess of electricity, which gets exported**. Assuming that electricity is not exported is therefore not always consistent. 

Is this of concern?

**Comment by BjoernLaemmerzahl** [comment]
> On the bright side of things: our assumption that excess production of wind and solar is exported is likely not correct. Curtailment would probably be more realistic.

This is not correct. The export and import of Energy is constant for every country either implicit by market coupling (e.g. flow-based Market coupling) or explicit by auctioning of transmission capacities. The curtailment of generation capacities occurs only in cases where the transmission network is physically limited. For example in cases of strong wind in Northern German turbines have to be shut down because the grid cannot export to neighbouring regions. See more here: transparency.entsoe.eu
